server:
  port: 8080
setty:
  discovery:
    host: 127.0.0.1
    port: ${server.port}
    instance-name: c1
    app-id: 20000000
    service-url:
      hs: http://127.0.0.1:10001/api/registry
  base:
    app-code: 30000