server:
  port: 10003
setty:
  discovery:
    app-id: 100000000
    host: 127.0.0.1
    port: 10003
    instance-name: REGISTRY_2
    is-registry: true
    service-url:
      default-zone:
        http://127.0.0.1:10002/api/registry
  base:
    app-code: 10000