server:
  port: 10001
setty:
  discovery:
    app-id: 100000000
    host: 127.0.0.1
    port: ${server.port}
    instance-name: REGISTRY_1
    is-registry: true
    service-url:
      zone1: http://127.0.0.1:10001/api/registry
      zone2: http://127.0.0.1:10002/api/registry
    zone: zone1
    region: china-west
    availability-zones:
      china-west: zone1,zone2
  base:
    app-code: 10000