server:
  port: 10002
setty:
  discovery:
    app-id: 100000000
    host: 127.0.0.1
    port: 10002
    instance-name: REGISTRY_1
    is-registry: true
    service-url:
      default-zone:
        http://127.0.0.1:10003/api/registry
  base:
    app-code: 10000